Feature: Add JS and WASM support to the Compose extensions
ajalt/colormath pull request #50
Opened 2024-02-01 21:41 UTC by jordond

2024-02-02 18:33 UTC, ajalt requested changes

2024-02-02 18:33 UTC, ajalt commented on extensions/colormath-ext-jetpack-compose/build.gradle.kts
> +        browser()
We don't run browser tests, so no need for `browser()`

2024-02-02 18:33 UTC, ajalt commented on extensions/colormath-ext-jetpack-compose/build.gradle.kts
> +    @Suppress("OPT_IN_USAGE")
Let's use `@OptIn(ExperimentalWasmDsl::class)` instead. Let's match how we do the declarations for the [main module][1]

[1]: https://github.com/ajalt/colormath/blob/9ff469060467d478466315280c19d803e4dd2bcd/colormath/build.gradle.kts#L14-L17

2024-02-02 18:33 UTC, ajalt commented
Thanks! Just a couple of comments.

2024-02-02 18:40 UTC, jordond commented
Addressed the comments 👍

2024-02-03 18:17 UTC, ajalt commented
Ah, looks like compose-ui didn't publish a wasm artifact [until 1.6.0][1], which is still in beta. So I guess this PR will have to wait until they release 1.6.0.

[1]: https://repo1.maven.org/maven2/org/jetbrains/compose/ui/ui-graphics-wasm-js/

2024-02-03 19:19 UTC, jordond commented
Oh shoot, yeah I forgot about that. Hoping for a stable 1.6 soon 🤞

2024-02-15 23:02 UTC, closed without merging